// back-end-onthaal/src/main/front-end-reactjs/src/components/Header.js
import React, { Component, Fragment } from 'react';

class Header extends Component {
    render() {
        return (
            
            <div className="container" id="header_container">
  <p className="alignright marginTop30"><small></small></p>
  <h4>ONTHAAL APPLICATIE</h4>
  <nav className="navbar navbar-inverse">
    <div className="container-fluid">
      <div className="navbar-header">
        <a className="navbar-brand" routerLink="/welcome">Onthaal Application</a>
      </div>
      <ul className="nav navbar-nav">

        <li className="active"><a routerLink="/welcome">Home</a></li>

        <li className="dropdown" ><a className="dropdown-toggle" data-toggle="dropdown" >Students <span
          className="caret"></span></a>
          <ul className="dropdown-menu">
            <li><a routerLink="/list_students">List students</a></li>
            <li><a routerLink="/students">Add new student</a></li>
            <li><a >Search a student</a></li>
            <li><a routerLink="/list_students">Archive a student</a></li>
          </ul>
        </li>

        <li className="dropdown" ><a className="dropdown-toggle" data-toggle="dropdown" >Staff Members<span
          className="caret"></span></a>
          <ul className="dropdown-menu">
            <li><a routerLink="/list_staff">List of the staff members</a></li>
            <li><a routerLink="/staff">Add new staff member</a></li>
            <li><a routerLink="/staff">Search</a></li>
            <li><a routerLink="/list_staff">Archive a staff member</a></li>
          </ul>
        </li>

        <li className="dropdown"   ><a className="dropdown-toggle" data-toggle="dropdown" >All the people <span
          className="caret"></span></a>
          <ul className="dropdown-menu">
            <li><a routerLink="/people">List of the all the people</a></li>
            <li><a routerLink="/list_staff">Staff members</a></li>
            <li><a routerLink="/list_students">Students</a></li>
            <li><a routerLink="/people">Search</a></li>
            <li><a routerLink="/people">Archive someone</a></li>
          </ul>
        </li>

        <li className="dropdown"><a className="dropdown-toggle" data-toggle="dropdown" >Messages <span
          className="caret"></span></a>
          <ul className="dropdown-menu">
            <li><a routerLink="/messages">Add new message</a></li>
            <li><a routerLink="/list_messages">List messages</a></li>
            <li><a >Search messages</a></li>
            <li><a routerLink="/list_messages">Archive a message</a></li>
          </ul>
        </li>
        <li><a  routerLink="/login" className="nav-link">Login</a></li>
        <li><a  routerLink="/logout" className="nav-link">LogOut</a></li>
      </ul>
        <form className="navbar-form navbar-left" >
            <div className="input-group">
                <input type="text" className="form-control" placeholder="Search" />
                <div className="input-group-btn">
                    <button className="btn btn-default" type="submit">
                    <i className="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
  </nav>
</div>

        );
    }
}

export default Header;

// src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthenticationService } from '../service/authentication.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  today = Date.now();
  constructor(private loginService:AuthenticationService) { }

  ngOnInit() {
  }
  
  search(){
    
  }

}

<div class="container" id="header_container">
  <p class="alignright marginTop30"><small>{{today | date:'EEEE, MMMM d, y'}} </small></p>
  <h4>ONTHAAL APPLICATIE</h4>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" routerLink="/welcome">Onthaal Application</a>
      </div>
      <ul class="nav navbar-nav">

        <li class="active"><a routerLink="/welcome">Home</a></li>

        <li class="dropdown" *ngIf="loginService.isUserLoggedIn()"><a class="dropdown-toggle" data-toggle="dropdown" >Students <span
          class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a routerLink="/list_students">List students</a></li>
            <li><a routerLink="/students">Add new student</a></li>
            <li><a >Search a student</a></li>
            <li><a routerLink="/list_students">Archive a student</a></li>
          </ul>
        </li>

        <li class="dropdown" *ngIf="loginService.isUserLoggedIn()" ><a class="dropdown-toggle" data-toggle="dropdown" >Staff Members<span
          class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a routerLink="/list_staff">List of the staff members</a></li>
            <li><a routerLink="/staff">Add new staff member</a></li>
            <li><a routerLink="/staff">Search</a></li>
            <li><a routerLink="/list_staff">Archive a staff member</a></li>
          </ul>
        </li>

        <li class="dropdown"  *ngIf="loginService.isUserLoggedIn()" ><a class="dropdown-toggle" data-toggle="dropdown" >All the people <span
          class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a routerLink="/people">List of the all the people</a></li>
            <li><a routerLink="/list_staff">Staff members</a></li>
            <li><a routerLink="/list_students">Students</a></li>
            <li><a routerLink="/people">Search</a></li>
            <li><a routerLink="/people">Archive someone</a></li>
          </ul>
        </li>

        <li class="dropdown" *ngIf="loginService.isUserLoggedIn()"><a class="dropdown-toggle" data-toggle="dropdown" >Messages <span
          class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a routerLink="/messages">Add new message</a></li>
            <li><a routerLink="/list_messages">List messages</a></li>
            <li><a >Search messages</a></li>
            <li><a routerLink="/list_messages">Archive a message</a></li>
          </ul>
        </li>
        <li><a *ngIf="!loginService.isUserLoggedIn()" routerLink="/login" class="nav-link">Login</a></li>
        <li><a *ngIf="loginService.isUserLoggedIn()" routerLink="/logout" class="nav-link">LogOut</a></li>
      </ul>
      <form class="navbar-form navbar-left" (ngSubmit)="search()">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search">
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <i class="glyphicon glyphicon-search"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
  </nav>
</div><!--header_container-->
